### ISSUE TITLE
Players Kicked while going island home

### ISSUE THREAD

**Issue by Disorbs** [rlf/uSkyBlock#160]
So when ever we go home by /is home or /tpa to someone in the skyworld it turns black
and kicks the player out it does this randomly and another thing i noticed not sure if its 1.8 spigot
or uskyblock but people cant farm potatoes or carrots together after putting two down it breaks
them all? any clue im using uskyblock 2.0.1 the version before this updated one.

EDIT: another i noticed not sure if its suppose to do this but when ever we restart the the island
it looks all buggy and glitchy and black but it works but just looks odd.

**Comment by rlf** [comment]
What versions are you using?
Because, the "buggy island" is caused by a client-getting-out-of-sync with the server, and has been solved in later releases by porting players to spawn and then back.

**Comment by Disorbs** [comment]
im using v2.0.1-RC1.38

**Comment by rlf** [comment]
Please update to the latest, and re-test (RC1.56 I think it is)

**Comment by Disorbs** [comment]
just updated it and it still happens not sure how to show u but this is all that happens

[03:52:30] [Server thread/INFO]: Strafeola_ issued server command: /is home
[03:52:30] [Server thread/INFO]: Strafeola_ lost connection: Internal Exception: java.io.IOException: Connection reset by peer
[03:52:30] [Server thread/INFO]: Strafeola_ left the game.

**Comment by rlf** [comment]
Is it all players that experience this? or just the one? is it only the player that gets kicked, or is the server going down?

Reg. the potatoes and carrots - it sounds like another issue - shouldn't be anything to do with USB, unless you are using a wrong  version of World-Guard, and the region is somehow responsible for it.

**Comment by Disorbs** [comment]
no the server doesn't go down because others are still on when i get kicked and as of now only we have run into this not sure what is causing it but the potatoes and carrots needed torches/light apparently i guess lol

**Comment by Disorbs** [comment]
i still need help with this it also does it for others and i dont want my members to get annoyed and leave :(

**Comment by rlf** [comment]
It's hard to say, without more information.

Try doing `/timings on` before you try to teleport.
And once you get back in (from being kicked), do `/timings paste`.

Provided you are using Spigot.
That sometimes gives an indication to what is going wrong.

**Comment by Disorbs** [comment]
hello idk if i did it right but i did /timings off and tested it a bit and got kicked and came
back on and did /timings paste so here it is i hope you can help with this, thanks

http://timings.aikar.co/?url=9790216

**Comment by Disorbs** [comment]
this is still happening with the newest uskyblock update the timings are up there can u help, thanks

**Comment by dutchy1001** [comment]
Timings dont say anything to me, that's rlf's department. Can you post through pastebin your server log, from start till the first player logs in. This would help me see what is used or what is missing. 

Sorry it takes so long but we tried to reproduce these errors but we can't for some(and that is frustrating) reason. 
This is either that there can be "corrupt" files, this doesn't have to be from USB but can be from any plugin that uses teleports.

**Comment by Disorbs** [comment]
yes sorry i posted this on the forums but here is the start logs hopefully its all of it 

server start logs: http://pastebin.com/7aVVVuGS
Plugins Incase one of them overloads them when going home: http://i.gyazo.com/a45045d50089bc6aa84893e2dec3170e.png

**Comment by rlf** [comment]
Just a stupid question, but from where do they do `/is home`? 
Which world? Since this looks to be a bungee - I'd like to know more about the circumstances before/under/after the bug.

If you could pastebin a server-log of a player executing `/is h` it might be helpful.

**Comment by rlf** [comment]
Ohh, just saw you had that earlier - and it didn't say anything... weird.
One more comment, could you try to unload the `movemenow` plugin?

**Comment by Disorbs** [comment]
yeah well i did it again and got kicked lol http://pastebin.com/mHhWrjfR

also then only happens when we go to spawn (World) im guess it might be
from switch worlds because when players are on the skyworld or their island
or others island it never happens, but when they go to spawn or the shop (world)
and use the command /is home or /tpa to someone in the skyworld sometimes it kicks
them out usually 50% chance they will get kicked and its only them not the server shutting down.

**Comment by dutchy1001** [comment]
also the Marriage plugin is not compatible, best remove that too

**Comment by Disorbs** [comment]
the marriage seems to work just fine the only thing that doesn't work is whats stated at the server start
about crouch+kissing lol but i can if itll help

**Comment by dutchy1001** [comment]
sometimes plugins do partial work but can still cause problems. An other server had it too and removed it.

**Comment by Disorbs** [comment]
alright gotcha any news on the info i posted might help solve this?

**Comment by rlf** [comment]
Does it also happen if you set a home on your island, and teleport directly to that home from the spawn world?

**Comment by Disorbs** [comment]
like with essentials? idk have tried it
but with skyblock i tred switching the homes no luck

**Comment by rlf** [comment]
Well, the problem is Disorbs, that it's not really USB that is causing an error, it's USB that is generating some circumstances, that your server somehow decides to kick players.

The plugin doesn't crash, it simply puts the player in a position, where the client/server apparently stalls for too long.

**Comment by rlf** [comment]
What is your server-address? I'll try to join and see if I can spot the error.

**Comment by Disorbs** [comment]
ah yes it also does it with essentials /home and play.disorbs.net

**Comment by rlf** [comment]
Then I think we can close this?
It seems to be, either your world, or your server-config?

**Comment by Disorbs** [comment]
Aww well when you guys setup do you use the world (world) for spawn and then the skyworld only for islands?

**Comment by dutchy1001** [comment]
yes, if you make skyworld your default world (by changing it in the server.properties file) you will get errors. of you want the skywold to be default world were players join the server you should do that with multiverse and leave the server.proprties file alone.

**Comment by Disorbs** [comment]
Oh no I want the world to be spawn I just figured maybe this was the problem :/ any advice I should see where this problem is being caused?

**Comment by rlf** [comment]
Try removing all your plugins, and enable them one at a  time (checking the /home transisition between the two spots).

If it doesn't occur until uSkyBlock is enabled - we might have an issue.

**Comment by rlf** [comment]
Btw. make sure the first 3 plugins you enable, are Essentials, Multiverse and PlugMan :D Makes your life so much easier.

**Comment by Disorbs** [comment]
actually i found where exactly it does this error take a look maybe you can help with it or give me some tips

http://www.spigotmc.org/threads/users-kicked-when-teleporting-from-shop.45616/

unless its just a coincidence but idk

**Comment by dutchy1001** [comment]
I'm not sure were to go from this as it's not only happening with usb. As rlf sugested 1 by 1 adding the plugins you have is the best way to identify wich is the culprint.

**Comment by rlf** [comment]
Closing this one. If Disorbs find a reason it should be USB, he can open a new issue.
