### ISSUE TITLE
Make Player Names Not Caps Sensitive

### ISSUE THREAD

**Issue by TheMattVid** [rlf/uSkyBlock#186]
Currently, when using a dev command, you must use the exact caps of a player's username. It would be easier if caps sensitivity could be removed. This is not an important feature, but I think it would be beneficial.

**Comment by rlf** [comment]
You are using an old version of the plugin.
That issue has been resolved a while back.
Please re-test with the latest - and comment back.

**Comment by dutchy1001** [comment]
Tested all working for me

**Comment by TheMattVid** [comment]
Please allow for me to respond before dismissing something as a false report.

My original problem was on 2.0.1. I have updated to 2.1.17 and manually transferred over data of the config file and the problem still exists.

/dev goto monkybone_
This does not work.

/dev goto Monkybone_
This works.

**Comment by dutchy1001** [comment]
After I tested it on my testserver

**Comment by TheMattVid** [comment]
That tab feature is a feature that I was unaware of and it seems very useful. Thank you for that.

If capitalization doesn't matter in dev/usb commands, then I'm still not sure why it's not working on my end.

**Comment by dutchy1001** [comment]
I dont know that either why it's not working for the capitol and small letter for you. But with use of the TAB  it shouldnt make a differance. It also completes the commands either with the first letter or cycly through all the options. /usb Space TAB

**Comment by TheMattVid** [comment]
This tab method gives me player names with correct capitalization, anyway.

Also, I didn't feel like opening a new issue for this, but hitting tab when "/is" is typed results in the word "ban" appearing twice. Also, I'm not sure if the command should be "/is banlist", but right now, it only works as "/is balist".

**Comment by rlf** [comment]
Acknowledged. Fixed in the next release. Though, banlist is an alias for ban, they all do the same thing (list bans when no name, toggles ban when a name is there).
