### ISSUE TITLE
Chest is empty

### ISSUE THREAD

**Issue by MrFiliper** [rlf/uSkyBlock#732]
Hi, i have big problem with islands chest. Where island generated, chest is empty, but i have set items in config.

Name: �uSkyBlock�
Version: �2.5.0-SNAPSHOT�
Language: �cs (cs)�
 �------------------------------�-
�Server: �CraftBukkit git-Spigot-db6de12-18fbb24 (MC: 1.8.8)�
 �------------------------------�
 �Název: �Vault (�ENABLED)�
 �Verze: �1.5.6-b49�
 �------------------------------�
 �Název: �WorldEdit (�ENABLED)�
 �Verze: �6.1;no_git_id�
 �------------------------------�
 �Název: �WorldGuard (�ENABLED)�
 �Verze: �6.1�
 �------------------------------�
 �Název: �AsyncWorldEdit (�ENABLED)�
 �Verze: �2.2.2�
 �------------------------------�

**Comment by dutchy1001** [comment]
have you used data value's?
Any error in console?
Maybe update the uSkyblock plugin.....

**Comment by MrFiliper** [comment]
In console no error. Yes, I use data value´s. But, i still in version 1.8.

**Comment by dutchy1001** [comment]
data value's don't work on the chest items

**Comment by MrFiliper** [comment]
This is my chest items:     chestItems: 50:1 0:1 0:1 79:1 79:1 79:1 0:1 0:1 50:1 297:1 0:1 0:1 0:1 327:1 0:1 0:1 0:1 297:1 0:1 362:1 0:1 6:1 6:1 6:1 0:1 361:1 0:1

**Comment by dutchy1001** [comment]
maybe the **air** isnt working any more.
And let me guess you haven't updated USB yet?

**Comment by MrFiliper** [comment]
Because lot of plugins still not updated. Air work, and if i delete air, problém will still pending.

**Comment by dutchy1001** [comment]
Just because other plugins haven't  been updated doesn't mean you cant update USB. Later versions of USB work with both 1.8 and 1.9. Also not every plugin needs updating, just because it says in the description it's for 1.8 doesn't mean their not working in 1.9.
The versions of USB 2.5.xx have their fare share of issues which have been fixed in later versions.

Best version so far is now the v2.6.8 on [github](https://github.com/rlf/uSkyBlock/releases/tag/v2.6.8).

**Comment by MrFiliper** [comment]
I can update the server... But plugin where I using, still not updated and display errors.. But back to the point. Next days i update skyblock to v2.5.7 (1.8) and watch, creches problem persists.

**Comment by dutchy1001** [comment]
I give up on this. 
You go ahead and update to v2.5.7 as you know best. If I tell you v2.6.8 is compatible with 1.8 is totally rubbish and I'm not knowing what I talk about.
Considerer no more help from me here.

**Comment by rlf** [comment]
MrFiliper - you are now in bad-standing. I have reviewed the issues you have raised here, and so far you are only generating noise. Almost all the help we try to provide, is ignored by you - and almost all your issues is coming from your changes to our released plugin, misconfiguration or failure to update.

You can safely assume, that I will close (and ignore) any issues you raise in the future - we simply have other things to spent our time on, than waste it on you.
Br. R4
